Add SignUp API call
Hudi304/DISI_WEB_Front pull request #7
Opened 2022-03-03 15:18 UTC by sasaranAndrei

2022-03-03 15:59 UTC, Hudi304 reviewed
Nice 👍

2022-03-04 16:43 UTC, DMyrm requested changes

2022-03-04 16:43 UTC, DMyrm commented on src/pages/sign-up/sign-up.tsx
> +  function handleSignUp() {
Delete this function if it's not used

2022-03-07 07:11 UTC, filipvladilie approved these changes
Good Job!

2022-03-07 17:22 UTC, merged